// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * R​o​u​t​e​r
		 */
		title: string
	}
	sidebar: {
		/**
		 * O​p​e​n​ ​S​i​d​e​b​a​r
		 */
		openLabel: string
		/**
		 * C​l​o​s​e​ ​S​i​d​e​b​a​r
		 */
		closeLabel: string
		/**
		 * C​l​i​c​k​ ​t​h​e​ ​m​a​p​ ​t​o​ ​a​d​d​ ​w​a​y​p​o​i​n​t​s​ ​w​h​e​n​ ​t​h​e​ ​r​o​u​t​e​ ​t​o​o​l​ ​i​s​ ​a​c​t​i​v​e​.​ ​C​l​i​c​k​ ​a​ ​w​a​y​p​o​i​n​t​ ​m​a​r​k​e​r​ ​t​o​ ​r​e​m​o​v​e​ ​i​t​.
		 */
		footer: string
	}
	route: {
		/**
		 * W​a​y​p​o​i​n​t​s
		 */
		waypoints: string
		/**
		 * N​o​ ​w​a​y​p​o​i​n​t​s​ ​y​e​t​ ​—​ ​a​c​t​i​v​a​t​e​ ​t​h​e​ ​r​o​u​t​e​ ​t​o​o​l​ ​a​n​d​ ​c​l​i​c​k​ ​t​h​e​ ​m​a​p​.
		 */
		noWaypoints: string
		/**
		 * R​e​m​o​v​e​ ​w​a​y​p​o​i​n​t
		 */
		removeWaypoint: string
		/**
		 * +​ ​A​d​d​ ​w​a​y​p​o​i​n​t
		 */
		addWaypoint: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​a​l​c​u​l​a​t​i​n​g​ ​r​o​u​t​e​…
		 */
		calculating: string
		/**
		 * D​u​r​a​t​i​o​n
		 */
		duration: string
		/**
		 * D​i​s​t​a​n​c​e
		 */
		distance: string
		/**
		 * C​a​l​c​u​l​a​t​e​ ​r​o​u​t​e
		 */
		controlTitle: string
		/**
		 * A​v​o​i​d​ ​t​o​l​l​s
		 */
		avoidToll: string
		/**
		 * A​v​o​i​d​ ​f​e​r​r​i​e​s
		 */
		avoidFerry: string
	}
	locate: {
		control: {
			/**
			 * L​o​c​a​t​e​:​ ​o​f​f​ ​—​ ​c​l​i​c​k​ ​t​o​ ​e​n​a​b​l​e​ ​n​o​d​e​ ​s​n​a​p​p​i​n​g
			 */
			off: string
			/**
			 * L​o​c​a​t​e​:​ ​n​o​d​e​ ​—​ ​c​l​i​c​k​ ​t​o​ ​s​w​i​t​c​h​ ​t​o​ ​e​d​g​e​ ​s​n​a​p​p​i​n​g
			 */
			node: string
			/**
			 * L​o​c​a​t​e​:​ ​e​d​g​e​ ​—​ ​c​l​i​c​k​ ​t​o​ ​d​i​s​a​b​l​e
			 */
			edge: string
		}
		inspect: {
			/**
			 * I​n​s​p​e​c​t​e​d​ ​W​a​y
			 */
			titleWay: string
			/**
			 * I​n​s​p​e​c​t​e​d​ ​N​o​d​e
			 */
			titleNode: string
			/**
			 * O​S​M​ ​N​o​d​e​ ​I​D
			 */
			osmNodeId: string
			/**
			 * O​S​M​ ​W​a​y​ ​I​D
			 */
			osmWayId: string
			/**
			 * L​a​t
			 */
			lat: string
			/**
			 * L​o​n
			 */
			lon: string
			/**
			 * H​i​g​h​w​a​y
			 */
			highway: string
			/**
			 * M​a​x​ ​s​p​e​e​d
			 */
			maxSpeed: string
			/**
			 * {​s​p​e​e​d​}​ ​k​m​/​h
			 * @param {number} speed
			 */
			maxSpeedKmh: RequiredParams<'speed'>
			/**
			 * d​e​f​a​u​l​t
			 */
			maxSpeedDefault: string
			/**
			 * S​u​r​f​a​c​e​ ​q​u​a​l​i​t​y
			 */
			surfaceQuality: string
			highwayClass: {
				/**
				 * U​n​k​n​o​w​n
				 */
				Unknown: string
				/**
				 * M​o​t​o​r​w​a​y
				 */
				Motorway: string
				/**
				 * T​r​u​n​k
				 */
				Trunk: string
				/**
				 * P​r​i​m​a​r​y
				 */
				Primary: string
				/**
				 * S​e​c​o​n​d​a​r​y
				 */
				Secondary: string
				/**
				 * T​e​r​t​i​a​r​y
				 */
				Tertiary: string
				/**
				 * M​o​t​o​r​w​a​y​ ​L​i​n​k
				 */
				MotorwayLink: string
				/**
				 * T​r​u​n​k​ ​L​i​n​k
				 */
				TrunkLink: string
				/**
				 * P​r​i​m​a​r​y​ ​L​i​n​k
				 */
				PrimaryLink: string
				/**
				 * S​e​c​o​n​d​a​r​y​ ​L​i​n​k
				 */
				SecondaryLink: string
				/**
				 * T​e​r​t​i​a​r​y​ ​L​i​n​k
				 */
				TertiaryLink: string
				/**
				 * U​n​c​l​a​s​s​i​f​i​e​d
				 */
				Unclassified: string
				/**
				 * R​e​s​i​d​e​n​t​i​a​l
				 */
				Residential: string
				/**
				 * L​i​v​i​n​g​ ​S​t​r​e​e​t
				 */
				LivingStreet: string
				/**
				 * S​e​r​v​i​c​e
				 */
				Service: string
				/**
				 * T​r​a​c​k
				 */
				Track: string
				/**
				 * R​o​a​d
				 */
				Road: string
				/**
				 * P​e​d​e​s​t​r​i​a​n
				 */
				Pedestrian: string
				/**
				 * F​o​o​t​w​a​y
				 */
				Footway: string
				/**
				 * C​y​c​l​e​w​a​y
				 */
				Cycleway: string
				/**
				 * P​a​t​h
				 */
				Path: string
				/**
				 * B​r​i​d​l​e​w​a​y
				 */
				Bridleway: string
				/**
				 * F​e​r​r​y
				 */
				Ferry: string
			}
			surfaceQualityClass: {
				/**
				 * U​n​k​n​o​w​n
				 */
				Unknown: string
				/**
				 * E​x​c​e​l​l​e​n​t
				 */
				Excellent: string
				/**
				 * G​o​o​d
				 */
				Good: string
				/**
				 * I​n​t​e​r​m​e​d​i​a​t​e
				 */
				Intermediate: string
				/**
				 * B​a​d
				 */
				Bad: string
				/**
				 * V​e​r​y​ ​B​a​d
				 */
				VeryBad: string
				/**
				 * H​o​r​r​i​b​l​e
				 */
				Horrible: string
				/**
				 * I​m​p​a​s​s​a​b​l​e
				 */
				Impassable: string
			}
			/**
			 * C​o​u​n​t​r​y
			 */
			country: string
			/**
			 * L​e​n​g​t​h
			 */
			distM: string
			/**
			 * {​d​i​s​t​}​ ​m
			 * @param {number} dist
			 */
			distMValue: RequiredParams<'dist'>
			/**
			 * S​n​a​p​ ​f​r​a​c​t​i​o​n
			 */
			fraction: string
			/**
			 * F​l​a​g​s
			 */
			flags: string
			/**
			 * N​o​d​e​ ​f​l​a​g​s
			 */
			nodeFlags: string
			/**
			 * M​a​x​ ​h​e​i​g​h​t
			 */
			maxHeight: string
			/**
			 * M​a​x​ ​w​i​d​t​h
			 */
			maxWidth: string
			/**
			 * M​a​x​ ​w​e​i​g​h​t
			 */
			maxWeight: string
			/**
			 * {​v​a​l​}​ ​c​m​ ​(​{​m​}​ ​m​)
			 * @param {number} m
			 * @param {number} val
			 */
			cmValue: RequiredParams<'m' | 'val'>
			/**
			 * {​v​a​l​}​ ​k​g​ ​(​{​t​}​ ​t​)
			 * @param {number} t
			 * @param {number} val
			 */
			weightKgValue: RequiredParams<'t' | 'val'>
			/**
			 * F​r​o​m​ ​n​o​d​e
			 */
			fromNode: string
			/**
			 * T​o​ ​n​o​d​e
			 */
			toNode: string
			/**
			 * P​o​s​i​t​i​o​n
			 */
			position: string
		}
		wayFlags: {
			/**
			 * o​n​e​w​a​y
			 */
			oneway: string
			/**
			 * n​o​ ​m​o​t​o​r
			 */
			noMotor: string
			/**
			 * n​o​ ​b​i​c​y​c​l​e
			 */
			noBicycle: string
			/**
			 * n​o​ ​f​o​o​t
			 */
			noFoot: string
			/**
			 * n​o​ ​H​G​V
			 */
			noHgv: string
			/**
			 * t​o​l​l
			 */
			toll: string
			/**
			 * t​u​n​n​e​l
			 */
			tunnel: string
			/**
			 * b​r​i​d​g​e
			 */
			bridge: string
			/**
			 * f​e​r​r​y
			 */
			ferry: string
		}
		nodeFlags: {
			/**
			 * n​o​ ​m​o​t​o​r
			 */
			noMotor: string
			/**
			 * n​o​ ​b​i​c​y​c​l​e
			 */
			noBicycle: string
			/**
			 * n​o​ ​f​o​o​t
			 */
			noFoot: string
			/**
			 * n​o​ ​H​G​V
			 */
			noHgv: string
			/**
			 * t​r​a​f​f​i​c​ ​s​i​g​n​a​l​s
			 */
			trafficSignals: string
			/**
			 * t​o​l​l
			 */
			toll: string
		}
	}
	isochrone: {
		/**
		 * I​s​o​c​h​r​o​n​e
		 */
		controlTitle: string
		/**
		 * O​r​i​g​i​n
		 */
		origin: string
		/**
		 * A​c​t​i​v​a​t​e​ ​a​n​d​ ​c​l​i​c​k​ ​t​h​e​ ​m​a​p​ ​t​o​ ​s​e​t​ ​t​h​e​ ​o​r​i​g​i​n​.
		 */
		noOrigin: string
		/**
		 * U​n​i​t
		 */
		unit: string
		/**
		 * D​i​s​t​a​n​c​e​ ​(​k​m​)
		 */
		unitKm: string
		/**
		 * D​i​s​t​a​n​c​e​ ​(​m​i​)
		 */
		unitMi: string
		/**
		 * T​r​a​v​e​l​ ​t​i​m​e​ ​(​m​i​n​)
		 */
		unitMin: string
		/**
		 * R​a​n​g​e​s
		 */
		ranges: string
		/**
		 * +​ ​A​d​d​ ​r​a​n​g​e
		 */
		addRange: string
		/**
		 * R​e​m​o​v​e​ ​r​a​n​g​e
		 */
		removeRange: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​a​l​c​u​l​a​t​i​n​g​…
		 */
		calculating: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Router
		 */
		title: () => LocalizedString
	}
	sidebar: {
		/**
		 * Open Sidebar
		 */
		openLabel: () => LocalizedString
		/**
		 * Close Sidebar
		 */
		closeLabel: () => LocalizedString
		/**
		 * Click the map to add waypoints when the route tool is active. Click a waypoint marker to remove it.
		 */
		footer: () => LocalizedString
	}
	route: {
		/**
		 * Waypoints
		 */
		waypoints: () => LocalizedString
		/**
		 * No waypoints yet — activate the route tool and click the map.
		 */
		noWaypoints: () => LocalizedString
		/**
		 * Remove waypoint
		 */
		removeWaypoint: () => LocalizedString
		/**
		 * + Add waypoint
		 */
		addWaypoint: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Calculating route…
		 */
		calculating: () => LocalizedString
		/**
		 * Duration
		 */
		duration: () => LocalizedString
		/**
		 * Distance
		 */
		distance: () => LocalizedString
		/**
		 * Calculate route
		 */
		controlTitle: () => LocalizedString
		/**
		 * Avoid tolls
		 */
		avoidToll: () => LocalizedString
		/**
		 * Avoid ferries
		 */
		avoidFerry: () => LocalizedString
	}
	locate: {
		control: {
			/**
			 * Locate: off — click to enable node snapping
			 */
			off: () => LocalizedString
			/**
			 * Locate: node — click to switch to edge snapping
			 */
			node: () => LocalizedString
			/**
			 * Locate: edge — click to disable
			 */
			edge: () => LocalizedString
		}
		inspect: {
			/**
			 * Inspected Way
			 */
			titleWay: () => LocalizedString
			/**
			 * Inspected Node
			 */
			titleNode: () => LocalizedString
			/**
			 * OSM Node ID
			 */
			osmNodeId: () => LocalizedString
			/**
			 * OSM Way ID
			 */
			osmWayId: () => LocalizedString
			/**
			 * Lat
			 */
			lat: () => LocalizedString
			/**
			 * Lon
			 */
			lon: () => LocalizedString
			/**
			 * Highway
			 */
			highway: () => LocalizedString
			/**
			 * Max speed
			 */
			maxSpeed: () => LocalizedString
			/**
			 * {speed} km/h
			 */
			maxSpeedKmh: (arg: { speed: number }) => LocalizedString
			/**
			 * default
			 */
			maxSpeedDefault: () => LocalizedString
			/**
			 * Surface quality
			 */
			surfaceQuality: () => LocalizedString
			highwayClass: {
				/**
				 * Unknown
				 */
				Unknown: () => LocalizedString
				/**
				 * Motorway
				 */
				Motorway: () => LocalizedString
				/**
				 * Trunk
				 */
				Trunk: () => LocalizedString
				/**
				 * Primary
				 */
				Primary: () => LocalizedString
				/**
				 * Secondary
				 */
				Secondary: () => LocalizedString
				/**
				 * Tertiary
				 */
				Tertiary: () => LocalizedString
				/**
				 * Motorway Link
				 */
				MotorwayLink: () => LocalizedString
				/**
				 * Trunk Link
				 */
				TrunkLink: () => LocalizedString
				/**
				 * Primary Link
				 */
				PrimaryLink: () => LocalizedString
				/**
				 * Secondary Link
				 */
				SecondaryLink: () => LocalizedString
				/**
				 * Tertiary Link
				 */
				TertiaryLink: () => LocalizedString
				/**
				 * Unclassified
				 */
				Unclassified: () => LocalizedString
				/**
				 * Residential
				 */
				Residential: () => LocalizedString
				/**
				 * Living Street
				 */
				LivingStreet: () => LocalizedString
				/**
				 * Service
				 */
				Service: () => LocalizedString
				/**
				 * Track
				 */
				Track: () => LocalizedString
				/**
				 * Road
				 */
				Road: () => LocalizedString
				/**
				 * Pedestrian
				 */
				Pedestrian: () => LocalizedString
				/**
				 * Footway
				 */
				Footway: () => LocalizedString
				/**
				 * Cycleway
				 */
				Cycleway: () => LocalizedString
				/**
				 * Path
				 */
				Path: () => LocalizedString
				/**
				 * Bridleway
				 */
				Bridleway: () => LocalizedString
				/**
				 * Ferry
				 */
				Ferry: () => LocalizedString
			}
			surfaceQualityClass: {
				/**
				 * Unknown
				 */
				Unknown: () => LocalizedString
				/**
				 * Excellent
				 */
				Excellent: () => LocalizedString
				/**
				 * Good
				 */
				Good: () => LocalizedString
				/**
				 * Intermediate
				 */
				Intermediate: () => LocalizedString
				/**
				 * Bad
				 */
				Bad: () => LocalizedString
				/**
				 * Very Bad
				 */
				VeryBad: () => LocalizedString
				/**
				 * Horrible
				 */
				Horrible: () => LocalizedString
				/**
				 * Impassable
				 */
				Impassable: () => LocalizedString
			}
			/**
			 * Country
			 */
			country: () => LocalizedString
			/**
			 * Length
			 */
			distM: () => LocalizedString
			/**
			 * {dist} m
			 */
			distMValue: (arg: { dist: number }) => LocalizedString
			/**
			 * Snap fraction
			 */
			fraction: () => LocalizedString
			/**
			 * Flags
			 */
			flags: () => LocalizedString
			/**
			 * Node flags
			 */
			nodeFlags: () => LocalizedString
			/**
			 * Max height
			 */
			maxHeight: () => LocalizedString
			/**
			 * Max width
			 */
			maxWidth: () => LocalizedString
			/**
			 * Max weight
			 */
			maxWeight: () => LocalizedString
			/**
			 * {val} cm ({m} m)
			 */
			cmValue: (arg: { m: number, val: number }) => LocalizedString
			/**
			 * {val} kg ({t} t)
			 */
			weightKgValue: (arg: { t: number, val: number }) => LocalizedString
			/**
			 * From node
			 */
			fromNode: () => LocalizedString
			/**
			 * To node
			 */
			toNode: () => LocalizedString
			/**
			 * Position
			 */
			position: () => LocalizedString
		}
		wayFlags: {
			/**
			 * oneway
			 */
			oneway: () => LocalizedString
			/**
			 * no motor
			 */
			noMotor: () => LocalizedString
			/**
			 * no bicycle
			 */
			noBicycle: () => LocalizedString
			/**
			 * no foot
			 */
			noFoot: () => LocalizedString
			/**
			 * no HGV
			 */
			noHgv: () => LocalizedString
			/**
			 * toll
			 */
			toll: () => LocalizedString
			/**
			 * tunnel
			 */
			tunnel: () => LocalizedString
			/**
			 * bridge
			 */
			bridge: () => LocalizedString
			/**
			 * ferry
			 */
			ferry: () => LocalizedString
		}
		nodeFlags: {
			/**
			 * no motor
			 */
			noMotor: () => LocalizedString
			/**
			 * no bicycle
			 */
			noBicycle: () => LocalizedString
			/**
			 * no foot
			 */
			noFoot: () => LocalizedString
			/**
			 * no HGV
			 */
			noHgv: () => LocalizedString
			/**
			 * traffic signals
			 */
			trafficSignals: () => LocalizedString
			/**
			 * toll
			 */
			toll: () => LocalizedString
		}
	}
	isochrone: {
		/**
		 * Isochrone
		 */
		controlTitle: () => LocalizedString
		/**
		 * Origin
		 */
		origin: () => LocalizedString
		/**
		 * Activate and click the map to set the origin.
		 */
		noOrigin: () => LocalizedString
		/**
		 * Unit
		 */
		unit: () => LocalizedString
		/**
		 * Distance (km)
		 */
		unitKm: () => LocalizedString
		/**
		 * Distance (mi)
		 */
		unitMi: () => LocalizedString
		/**
		 * Travel time (min)
		 */
		unitMin: () => LocalizedString
		/**
		 * Ranges
		 */
		ranges: () => LocalizedString
		/**
		 * + Add range
		 */
		addRange: () => LocalizedString
		/**
		 * Remove range
		 */
		removeRange: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Calculating…
		 */
		calculating: () => LocalizedString
	}
}

export type Formatters = {}
