// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	app: {
		/**
		 * R​o​u​t​e​r
		 */
		title: string
	}
	sidebar: {
		/**
		 * O​p​e​n​ ​S​i​d​e​b​a​r
		 */
		openLabel: string
		/**
		 * C​l​o​s​e​ ​S​i​d​e​b​a​r
		 */
		closeLabel: string
		/**
		 * C​l​i​c​k​ ​t​h​e​ ​m​a​p​ ​t​o​ ​a​d​d​ ​w​a​y​p​o​i​n​t​s​ ​w​h​e​n​ ​t​h​e​ ​r​o​u​t​e​ ​t​o​o​l​ ​i​s​ ​a​c​t​i​v​e​.​ ​C​l​i​c​k​ ​a​ ​w​a​y​p​o​i​n​t​ ​m​a​r​k​e​r​ ​t​o​ ​r​e​m​o​v​e​ ​i​t​.
		 */
		footer: string
	}
	route: {
		/**
		 * W​a​y​p​o​i​n​t​s
		 */
		waypoints: string
		/**
		 * N​o​ ​w​a​y​p​o​i​n​t​s​ ​y​e​t​ ​—​ ​a​c​t​i​v​a​t​e​ ​t​h​e​ ​r​o​u​t​e​ ​t​o​o​l​ ​a​n​d​ ​c​l​i​c​k​ ​t​h​e​ ​m​a​p​.
		 */
		noWaypoints: string
		/**
		 * R​e​m​o​v​e​ ​w​a​y​p​o​i​n​t
		 */
		removeWaypoint: string
		/**
		 * +​ ​A​d​d​ ​w​a​y​p​o​i​n​t
		 */
		addWaypoint: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​a​l​c​u​l​a​t​i​n​g​ ​r​o​u​t​e​…
		 */
		calculating: string
		/**
		 * D​u​r​a​t​i​o​n
		 */
		duration: string
		/**
		 * D​i​s​t​a​n​c​e
		 */
		distance: string
		/**
		 * C​a​l​c​u​l​a​t​e​ ​r​o​u​t​e
		 */
		controlTitle: string
	}
	locate: {
		control: {
			/**
			 * L​o​c​a​t​e​:​ ​o​f​f​ ​—​ ​c​l​i​c​k​ ​t​o​ ​e​n​a​b​l​e​ ​n​o​d​e​ ​s​n​a​p​p​i​n​g
			 */
			off: string
			/**
			 * L​o​c​a​t​e​:​ ​n​o​d​e​ ​—​ ​c​l​i​c​k​ ​t​o​ ​s​w​i​t​c​h​ ​t​o​ ​e​d​g​e​ ​s​n​a​p​p​i​n​g
			 */
			node: string
			/**
			 * L​o​c​a​t​e​:​ ​e​d​g​e​ ​—​ ​c​l​i​c​k​ ​t​o​ ​d​i​s​a​b​l​e
			 */
			edge: string
		}
		inspect: {
			/**
			 * I​n​s​p​e​c​t​e​d​ ​W​a​y
			 */
			titleWay: string
			/**
			 * I​n​s​p​e​c​t​e​d​ ​N​o​d​e
			 */
			titleNode: string
			/**
			 * O​S​M​ ​N​o​d​e​ ​I​D
			 */
			osmNodeId: string
			/**
			 * O​S​M​ ​W​a​y​ ​I​D
			 */
			osmWayId: string
			/**
			 * L​a​t
			 */
			lat: string
			/**
			 * L​o​n
			 */
			lon: string
			/**
			 * H​i​g​h​w​a​y
			 */
			highway: string
			/**
			 * M​a​x​ ​s​p​e​e​d
			 */
			maxSpeed: string
			/**
			 * {​s​p​e​e​d​}​ ​k​m​/​h
			 * @param {number} speed
			 */
			maxSpeedKmh: RequiredParams<'speed'>
			/**
			 * d​e​f​a​u​l​t
			 */
			maxSpeedDefault: string
			/**
			 * F​l​a​g​s
			 */
			flags: string
			/**
			 * F​r​o​m​ ​n​o​d​e
			 */
			fromNode: string
			/**
			 * T​o​ ​n​o​d​e
			 */
			toNode: string
			/**
			 * P​o​s​i​t​i​o​n
			 */
			position: string
		}
		flags: {
			/**
			 * o​n​e​w​a​y
			 */
			oneway: string
			/**
			 * n​o​ ​m​o​t​o​r
			 */
			noMotor: string
			/**
			 * n​o​ ​b​i​c​y​c​l​e
			 */
			noBicycle: string
			/**
			 * n​o​ ​f​o​o​t
			 */
			noFoot: string
			/**
			 * n​o​ ​H​G​V
			 */
			noHgv: string
		}
	}
	isochrone: {
		/**
		 * I​s​o​c​h​r​o​n​e
		 */
		controlTitle: string
		/**
		 * O​r​i​g​i​n
		 */
		origin: string
		/**
		 * A​c​t​i​v​a​t​e​ ​a​n​d​ ​c​l​i​c​k​ ​t​h​e​ ​m​a​p​ ​t​o​ ​s​e​t​ ​t​h​e​ ​o​r​i​g​i​n​.
		 */
		noOrigin: string
		/**
		 * U​n​i​t
		 */
		unit: string
		/**
		 * D​i​s​t​a​n​c​e​ ​(​k​m​)
		 */
		unitKm: string
		/**
		 * D​i​s​t​a​n​c​e​ ​(​m​i​)
		 */
		unitMi: string
		/**
		 * T​r​a​v​e​l​ ​t​i​m​e​ ​(​m​i​n​)
		 */
		unitMin: string
		/**
		 * R​a​n​g​e​s
		 */
		ranges: string
		/**
		 * +​ ​A​d​d​ ​r​a​n​g​e
		 */
		addRange: string
		/**
		 * R​e​m​o​v​e​ ​r​a​n​g​e
		 */
		removeRange: string
		/**
		 * C​l​e​a​r
		 */
		clear: string
		/**
		 * C​a​l​c​u​l​a​t​i​n​g​…
		 */
		calculating: string
	}
}

export type TranslationFunctions = {
	app: {
		/**
		 * Router
		 */
		title: () => LocalizedString
	}
	sidebar: {
		/**
		 * Open Sidebar
		 */
		openLabel: () => LocalizedString
		/**
		 * Close Sidebar
		 */
		closeLabel: () => LocalizedString
		/**
		 * Click the map to add waypoints when the route tool is active. Click a waypoint marker to remove it.
		 */
		footer: () => LocalizedString
	}
	route: {
		/**
		 * Waypoints
		 */
		waypoints: () => LocalizedString
		/**
		 * No waypoints yet — activate the route tool and click the map.
		 */
		noWaypoints: () => LocalizedString
		/**
		 * Remove waypoint
		 */
		removeWaypoint: () => LocalizedString
		/**
		 * + Add waypoint
		 */
		addWaypoint: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Calculating route…
		 */
		calculating: () => LocalizedString
		/**
		 * Duration
		 */
		duration: () => LocalizedString
		/**
		 * Distance
		 */
		distance: () => LocalizedString
		/**
		 * Calculate route
		 */
		controlTitle: () => LocalizedString
	}
	locate: {
		control: {
			/**
			 * Locate: off — click to enable node snapping
			 */
			off: () => LocalizedString
			/**
			 * Locate: node — click to switch to edge snapping
			 */
			node: () => LocalizedString
			/**
			 * Locate: edge — click to disable
			 */
			edge: () => LocalizedString
		}
		inspect: {
			/**
			 * Inspected Way
			 */
			titleWay: () => LocalizedString
			/**
			 * Inspected Node
			 */
			titleNode: () => LocalizedString
			/**
			 * OSM Node ID
			 */
			osmNodeId: () => LocalizedString
			/**
			 * OSM Way ID
			 */
			osmWayId: () => LocalizedString
			/**
			 * Lat
			 */
			lat: () => LocalizedString
			/**
			 * Lon
			 */
			lon: () => LocalizedString
			/**
			 * Highway
			 */
			highway: () => LocalizedString
			/**
			 * Max speed
			 */
			maxSpeed: () => LocalizedString
			/**
			 * {speed} km/h
			 */
			maxSpeedKmh: (arg: { speed: number }) => LocalizedString
			/**
			 * default
			 */
			maxSpeedDefault: () => LocalizedString
			/**
			 * Flags
			 */
			flags: () => LocalizedString
			/**
			 * From node
			 */
			fromNode: () => LocalizedString
			/**
			 * To node
			 */
			toNode: () => LocalizedString
			/**
			 * Position
			 */
			position: () => LocalizedString
		}
		flags: {
			/**
			 * oneway
			 */
			oneway: () => LocalizedString
			/**
			 * no motor
			 */
			noMotor: () => LocalizedString
			/**
			 * no bicycle
			 */
			noBicycle: () => LocalizedString
			/**
			 * no foot
			 */
			noFoot: () => LocalizedString
			/**
			 * no HGV
			 */
			noHgv: () => LocalizedString
		}
	}
	isochrone: {
		/**
		 * Isochrone
		 */
		controlTitle: () => LocalizedString
		/**
		 * Origin
		 */
		origin: () => LocalizedString
		/**
		 * Activate and click the map to set the origin.
		 */
		noOrigin: () => LocalizedString
		/**
		 * Unit
		 */
		unit: () => LocalizedString
		/**
		 * Distance (km)
		 */
		unitKm: () => LocalizedString
		/**
		 * Distance (mi)
		 */
		unitMi: () => LocalizedString
		/**
		 * Travel time (min)
		 */
		unitMin: () => LocalizedString
		/**
		 * Ranges
		 */
		ranges: () => LocalizedString
		/**
		 * + Add range
		 */
		addRange: () => LocalizedString
		/**
		 * Remove range
		 */
		removeRange: () => LocalizedString
		/**
		 * Clear
		 */
		clear: () => LocalizedString
		/**
		 * Calculating…
		 */
		calculating: () => LocalizedString
	}
}

export type Formatters = {}
